### PR TITLE
Feat/COCO-STQA-18: Added a back to top button

### PR DESCRIPTION
**Pull request by Flip-HH**
Okay third time is the charm

Added a back to top button with js and css files.

Added links in htmlHeader.tag

Added button in menu.tag

### CODE REVIEW

**Review by LouisChoiniere — DISMISSED** [review]
Sure bud

**Review by Shayminn — DISMISSED** [review]
Looks nice! Keep up the good work.

**Review by LouisChoiniere — APPROVED** [review]
Ok

**Review by Shayminn — APPROVED** [review]
Looks great!

**Pull request merged**
