### PR TITLE
feat(Yeet-SQTA-27): Remove Pet

### PR DESCRIPTION
**Pull request by saoudmessaoudi**
Removing Pet functionality that didn't exist before is now implemented. 

Requirements: 

- Pet chosen must be removed from database
- Pet must be removed from the Pet List Display

Unit Tests created for this user story passed: 
image

Regression Tests Result : 
image

### CODE REVIEW

**Comment by Yuq140** [comment]
Review your pet controller class? The test didn't pass and it said there's a problem with the petController class

**Comment by saoudmessaoudi** [comment]
Fixed the problem =D

**Review by Yuq140 — DISMISSED** [review]
Looks Great To Me

**Review by Floudrai — DISMISSED** [review]

**Comment by Floudrai** [comment]
looks good to me

**Comment by saoudmessaoudi** [comment]
Re resolved Merge conflict

**Review by Floudrai — APPROVED** [review]

**Comment by Floudrai** [comment]
ok

**Review by Yuq140 — APPROVED** [review]
That's a lot of merging conflict but looks good to me

**Pull request merged**
