### PR TITLE
feat(APPT-SQTA) View All Appointments 1.0

### PR DESCRIPTION
**Pull request by Rakaesa**
The first iteration of the 'view all appointments' front-end work for Sprint 1.

### CODE REVIEW

**Review by Colorin09 — APPROVED** [review]
Looks good!

**Review by sylveon — CHANGES_REQUESTED** [review]
Needs unit tests

**Review by Colorin09 — CHANGES_REQUESTED** [review]
Implement the methods you have in ClinicServices into ClinicServicesImpl

**Comment by sylveon** [comment]
Can you add tests for the new method you added on the repository?

**Review by sylveon — APPROVED** [review]

**Review by Colorin09 — APPROVED** [review]

**Pull request merged**
