### PR TITLE
feat(OWRT-STQA-127) : Improve_Input_Fields_Validation

### PR DESCRIPTION
**Pull request by antoheb**
When the user will add or update an existing owner, validation has been added on each input field. Validation is made to ensure the data has the correct format. Also, a new field called state has been added to the owner table.

### CODE REVIEW

**Review by WilliamMeroz — CHANGES_REQUESTED** [review]
There seems to be unnecessary  dependencies in your pom.xml file. Also, your <th> tags in your ownersList.jsp file do not have a style attribute like the others. Other than that, really good work!

**Review by s00220021 — DISMISSED** [review]
Wow, amazing work bro. Pretty complicated stuff that's def over my head. Great tests also

**Review by WilliamMeroz — APPROVED** [review]
Well done! I'm glad you managed to fix your bug!

**Review by s00220021 — APPROVED** [review]
Great bro!

**Pull request merged**
