### PR TITLE
feat(COCO-STQA-23): Added calendar comment

### PR DESCRIPTION
**Pull request by LouisChoiniere**

### CODE REVIEW

**Comment by Flip-HH** [comment]
This is good

**Review by Flip-HH — DISMISSED** [review]
Great Code !

**Review by Shayminn — DISMISSED** [review]
Pulchritudinous

**Review by Flip-HH — APPROVED** [review]
I like your code G

**Review by Shayminn — APPROVED** [review]
Beautiful comment

**Pull request closed without merging**
